# Generated by Django 6.0.1 on 2026-03-14 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Tên dịch vụ")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="Giá"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Đơn vị"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Giá dịch vụ",
                "verbose_name_plural": "Giá dịch vụ",
                "db_table": "service_prices",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DataPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module", models.CharField(max_length=50, verbose_name="Module")),
                (
                    "data_scope",
                    models.CharField(
                        help_text="all, own, warehouse, etc.",
                        max_length=50,
                        verbose_name="Phạm vi dữ liệu",
                    ),
                ),
                (
                    "warehouse_ids",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Danh sách ID kho (phân cách bởi dấu phẩy)",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người dùng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phân quyền dữ liệu",
                "verbose_name_plural": "Phân quyền dữ liệu",
                "db_table": "data_permissions",
            },
        ),
        migrations.CreateModel(
            name="RoleGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Tên nhóm vai trò"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_group",
                        to="auth.group",
                        verbose_name="Django Group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nhóm vai trò",
                "verbose_name_plural": "Nhóm vai trò",
                "db_table": "role_groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Tạo mới"),
                            ("update", "Cập nhật"),
                            ("delete", "Xóa"),
                            ("login", "Đăng nhập"),
                            ("logout", "Đăng xuất"),
                            ("export", "Xuất dữ liệu"),
                            ("import", "Nhập dữ liệu"),
                        ],
                        max_length=20,
                        verbose_name="Hành động",
                    ),
                ),
                ("module", models.CharField(max_length=50, verbose_name="Module")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID đối tượng",
                    ),
                ),
                (
                    "old_data",
                    models.JSONField(blank=True, null=True, verbose_name="Dữ liệu cũ"),
                ),
                (
                    "new_data",
                    models.JSONField(blank=True, null=True, verbose_name="Dữ liệu mới"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Địa chỉ IP"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người dùng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log hệ thống",
                "verbose_name_plural": "Log hệ thống",
                "db_table": "system_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Số điện thoại",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        verbose_name="Ảnh đại diện",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Địa chỉ"),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Phòng ban"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Chức vụ"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hồ sơ người dùng",
                "verbose_name_plural": "Hồ sơ người dùng",
                "db_table": "user_profiles",
            },
        ),
        migrations.CreateModel(
            name="ModulePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("orders", "Quản lý đơn hàng"),
                            ("products", "Quản lý sản phẩm"),
                            ("customers", "Quản lý khách hàng"),
                            ("finance", "Thu chi"),
                            ("reports", "Báo cáo"),
                            ("system", "Quản lý hệ thống"),
                        ],
                        max_length=50,
                        verbose_name="Module",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "Xem"),
                            ("add", "Thêm"),
                            ("edit", "Sửa"),
                            ("delete", "Xóa"),
                            ("export", "Xuất"),
                            ("approve", "Duyệt"),
                        ],
                        max_length=20,
                        verbose_name="Hành động",
                    ),
                ),
                (
                    "is_allowed",
                    models.BooleanField(default=False, verbose_name="Cho phép"),
                ),
                (
                    "role_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="system_management.rolegroup",
                        verbose_name="Nhóm vai trò",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phân quyền module",
                "verbose_name_plural": "Phân quyền module",
                "db_table": "module_permissions",
                "unique_together": {("role_group", "module", "action")},
            },
        ),
    ]
