# Generated by Django 6.0.1 on 2026-03-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrinterSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Tên máy in")),
                (
                    "printer_type",
                    models.CharField(
                        choices=[
                            ("lan", "Máy in LAN (Mạng)"),
                            ("usb", "Máy in USB"),
                            ("bluetooth", "Máy in Bluetooth"),
                        ],
                        default="lan",
                        max_length=20,
                        verbose_name="Loại kết nối",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Địa chỉ IP"
                    ),
                ),
                ("port", models.IntegerField(default=9100, verbose_name="Cổng (Port)")),
                (
                    "paper_size",
                    models.CharField(
                        choices=[
                            ("A4", "A4 (210 x 297 mm)"),
                            ("A5", "A5 (148 x 210 mm)"),
                            ("80mm", "Giấy nhiệt 80mm"),
                            ("58mm", "Giấy nhiệt 58mm"),
                            ("letter", "Letter (216 x 279 mm)"),
                        ],
                        default="A4",
                        max_length=20,
                        verbose_name="Khổ giấy",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Máy in mặc định"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cài đặt máy in",
                "verbose_name_plural": "Cài đặt máy in",
                "db_table": "printer_settings",
                "ordering": ["-is_default", "name"],
            },
        ),
    ]
