# Generated by Django 6.0.1 on 2026-03-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_management", "0002_printersetting"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("retail", "Bán lẻ / Siêu thị"),
                            ("spa", "Spa / Massage"),
                            ("fashion", "Thời trang / Giày dép"),
                            ("fnb", "Nhà hàng / Quán café"),
                            ("pharmacy", "Nhà thuốc"),
                            ("custom", "Tùy chỉnh"),
                        ],
                        default="custom",
                        max_length=20,
                        verbose_name="Mô hình kinh doanh",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        default="Doanh nghiệp",
                        max_length=255,
                        verbose_name="Tên doanh nghiệp",
                    ),
                ),
                (
                    "mod_orders",
                    models.BooleanField(default=True, verbose_name="Đơn hàng"),
                ),
                (
                    "mod_quotations",
                    models.BooleanField(default=True, verbose_name="Báo giá"),
                ),
                (
                    "mod_returns",
                    models.BooleanField(default=True, verbose_name="Trả hàng"),
                ),
                (
                    "mod_packaging",
                    models.BooleanField(default=True, verbose_name="Đóng gói"),
                ),
                (
                    "mod_products",
                    models.BooleanField(default=True, verbose_name="Sản phẩm & Kho"),
                ),
                (
                    "mod_customers",
                    models.BooleanField(default=True, verbose_name="Khách hàng"),
                ),
                (
                    "mod_finance",
                    models.BooleanField(default=True, verbose_name="Thu chi"),
                ),
                (
                    "mod_reports",
                    models.BooleanField(default=True, verbose_name="Báo cáo"),
                ),
                (
                    "mod_spa",
                    models.BooleanField(default=False, verbose_name="Spa & Dịch vụ"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cấu hình mô hình KD",
                "verbose_name_plural": "Cấu hình mô hình KD",
                "db_table": "business_config",
            },
        ),
    ]
