# Generated by Django 6.0.1 on 2026-03-17 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_management", "0003_businessconfig"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Tên thương hiệu"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="brands/", verbose_name="Logo"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Hotline"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Website"),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, null=True, verbose_name="Địa chỉ trụ sở"
                    ),
                ),
                (
                    "tax_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Mã số thuế"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_brands",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Chủ sở hữu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thương hiệu",
                "verbose_name_plural": "Thương hiệu",
                "db_table": "brands",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Tên cửa hàng")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Mã cửa hàng"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="SĐT"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Địa chỉ"),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Tỉnh/Thành"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Quận/Huyện"
                    ),
                ),
                (
                    "open_time",
                    models.TimeField(blank=True, null=True, verbose_name="Giờ mở cửa"),
                ),
                (
                    "close_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Giờ đóng cửa"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stores",
                        to="system_management.brand",
                        verbose_name="Thương hiệu",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_stores",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Quản lý",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cửa hàng",
                "verbose_name_plural": "Cửa hàng",
                "db_table": "stores",
                "ordering": ["brand__name", "name"],
            },
        ),
    ]
