# Generated by Django 6.0.1 on 2026-03-17 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_management", "0004_brand_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_profiles",
                to="system_management.store",
                verbose_name="Cửa hàng",
            ),
        ),
    ]
