# Generated by Django 6.0.1 on 2026-03-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_management", "0005_userprofile_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="business_type",
            field=models.CharField(
                choices=[
                    ("retail", "Bán lẻ"),
                    ("restaurant", "Quán ăn"),
                    ("cafe", "Cafe"),
                    ("spa", "Spa"),
                ],
                default="retail",
                max_length=20,
                verbose_name="Mô hình kinh doanh",
            ),
        ),
    ]
