# Generated by Django 6.0.1 on 2026-03-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_management", "0006_brand_business_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessconfig",
            name="opt_quotation_salesperson",
            field=models.BooleanField(default=False, verbose_name="Hiện người báo giá"),
        ),
    ]
