# Generated by Django 6.0.1 on 2026-03-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_management", "0007_businessconfig_opt_quotation_salesperson"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessconfig",
            name="opt_order_bonus",
            field=models.BooleanField(
                default=False, verbose_name="Hiện tiền bonus trên hóa đơn"
            ),
        ),
        migrations.AddField(
            model_name="businessconfig",
            name="opt_order_salesperson",
            field=models.BooleanField(
                default=False, verbose_name="Hiện NV bán hàng trên hóa đơn"
            ),
        ),
        migrations.AddField(
            model_name="businessconfig",
            name="opt_order_server_staff",
            field=models.BooleanField(
                default=False, verbose_name="Hiện NV phục vụ trên hóa đơn"
            ),
        ),
    ]
