# Generated by Django 6.0.1 on 2026-03-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_management", "0008_businessconfig_opt_order_bonus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessconfig",
            name="opt_order_approver",
            field=models.BooleanField(
                default=False, verbose_name="Hiện người duyệt trên hóa đơn"
            ),
        ),
    ]
