# Generated by Django 6.0.1 on 2026-03-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_management", "0009_businessconfig_opt_order_approver"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessconfig",
            name="mod_cafe_tables",
            field=models.BooleanField(default=False, verbose_name="Quản lý bàn (Cafe)"),
        ),
        migrations.AddField(
            model_name="businessconfig",
            name="mod_pos",
            field=models.BooleanField(default=False, verbose_name="POS bán hàng nhanh"),
        ),
        migrations.AddField(
            model_name="businessconfig",
            name="opt_commission",
            field=models.BooleanField(default=False, verbose_name="Hoa hồng nhân viên"),
        ),
        migrations.AddField(
            model_name="businessconfig",
            name="opt_loyalty_points",
            field=models.BooleanField(
                default=False, verbose_name="Tích điểm khách hàng"
            ),
        ),
        migrations.AddField(
            model_name="businessconfig",
            name="opt_loyalty_rate",
            field=models.IntegerField(
                default=10000, verbose_name="Mỗi X đồng = 1 điểm"
            ),
        ),
    ]
