# Generated by Django 6.0.1 on 2026-03-19 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_management", "0010_businessconfig_mod_cafe_tables_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessconfig",
            name="brand",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="business_config",
                to="system_management.brand",
                verbose_name="Thương hiệu",
            ),
        ),
    ]
