# Generated by Django 6.0.1 on 2026-04-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_management", "0011_businessconfig_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessconfig",
            name="opt_allow_negative_stock",
            field=models.BooleanField(
                default=False, verbose_name="Cho phép tồn âm (bán khi hết hàng)"
            ),
        ),
    ]
