# Generated by Django 6.0.1 on 2026-06-19 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_management", "0017_enable_product_images_for_quotation_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="rolegroup",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_groups",
                to="system_management.brand",
                verbose_name="Thương hiệu",
            ),
        ),
        migrations.AlterField(
            model_name="rolegroup",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Tên nhóm vai trò"),
        ),
        migrations.AlterUniqueTogether(
            name="rolegroup",
            unique_together={("brand", "name")},
        ),
    ]
