# Generated by Django 6.0.1 on 2026-07-03 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_management", "0018_rolegroup_brand_alter_rolegroup_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="printersetting",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="printer_settings",
                to="system_management.brand",
                verbose_name="Nhãn hiệu / thương hiệu",
            ),
        ),
    ]
