# Generated by Django 6.0.1 on 2026-07-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_management", "0019_printersetting_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Tên thương hiệu"),
        ),
        migrations.AddField(
            model_name="brand",
            name="brand_type",
            field=models.CharField(
                choices=[("company", "Công ty"), ("print_label", "Nhãn hiệu in")],
                default="company",
                max_length=20,
                verbose_name="Loại thương hiệu",
            ),
        ),
        migrations.AddConstraint(
            model_name="brand",
            constraint=models.UniqueConstraint(
                fields=("owner", "brand_type", "name"),
                name="uniq_brand_owner_type_name",
            ),
        ),
    ]
