# Generated by Django 6.0.1 on 2026-03-14 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceiptItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="Số lượng")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Đơn giá",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Thành tiền",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt_sale_items",
                        to="products.product",
                        verbose_name="Sản phẩm",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="finance.receipt",
                        verbose_name="Phiếu thu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chi tiết phiếu thu",
                "verbose_name_plural": "Chi tiết phiếu thu",
                "db_table": "receipt_items",
            },
        ),
    ]
