# Generated by Django 6.0.1 on 2026-03-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_receiptitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashbook",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ngày xóa"),
        ),
        migrations.AddField(
            model_name="cashbook",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Đã xóa"),
        ),
        migrations.AddField(
            model_name="financecategory",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ngày xóa"),
        ),
        migrations.AddField(
            model_name="financecategory",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Đã xóa"),
        ),
        migrations.AddField(
            model_name="payment",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ngày xóa"),
        ),
        migrations.AddField(
            model_name="payment",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Đã xóa"),
        ),
        migrations.AddField(
            model_name="receipt",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ngày xóa"),
        ),
        migrations.AddField(
            model_name="receipt",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Đã xóa"),
        ),
    ]
