# Generated by Django 6.0.1 on 2026-03-14 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_cashbook_deleted_at_cashbook_is_deleted_and_more"),
        ("orders", "0002_order_deleted_at_order_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receipts",
                to="orders.order",
                verbose_name="Đơn hàng",
            ),
        ),
    ]
