# Generated by Django 6.0.1 on 2026-03-15 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_receipt_order"),
        ("products", "0003_productvariant"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="goods_receipt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="products.goodsreceipt",
                verbose_name="Phiếu nhập hàng",
            ),
        ),
    ]
