# Generated by Django 6.0.1 on 2026-03-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_payment_goods_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.IntegerField(
                choices=[(1, "Tiền mặt"), (2, "Chuyển khoản")],
                default=1,
                verbose_name="Hình thức thanh toán",
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="payment_method",
            field=models.IntegerField(
                choices=[(1, "Tiền mặt"), (2, "Chuyển khoản")],
                default=1,
                verbose_name="Hình thức thanh toán",
            ),
        ),
    ]
