# Generated by Django 6.0.1 on 2026-03-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_payment_payment_method_receipt_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.IntegerField(
                choices=[(1, "Tiền mặt"), (2, "Chuyển khoản")],
                default=2,
                verbose_name="Hình thức thanh toán",
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="payment_method",
            field=models.IntegerField(
                choices=[(1, "Tiền mặt"), (2, "Chuyển khoản")],
                default=2,
                verbose_name="Hình thức thanh toán",
            ),
        ),
    ]
