# Generated by Django 6.0.1 on 2026-04-13 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0008_payment_store_receipt_store"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethodOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Đã xóa"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ngày xóa"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Mã phương thức"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Tên phương thức"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
                (
                    "legacy_type",
                    models.IntegerField(
                        choices=[(1, "Tiền mặt"), (2, "Chuyển khoản"), (3, "Khác")],
                        default=3,
                        verbose_name="Loại chuẩn",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Thứ tự")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_cash_book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_method_defaults",
                        to="finance.cashbook",
                        verbose_name="Tài khoản mặc định",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phương thức thanh toán",
                "verbose_name_plural": "Phương thức thanh toán",
                "db_table": "payment_method_options",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="finance.paymentmethodoption",
                verbose_name="Phương thức thanh toán",
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="payment_method_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receipts",
                to="finance.paymentmethodoption",
                verbose_name="Phương thức thanh toán",
            ),
        ),
    ]
