# Generated by Django 6.0.1 on 2026-03-17 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0002_customer_deleted_at_customer_is_deleted_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Tên phòng")),
                (
                    "room_type",
                    models.IntegerField(
                        choices=[
                            (1, "Phòng thường"),
                            (2, "Phòng VIP"),
                            (3, "Phòng đôi"),
                        ],
                        default=1,
                        verbose_name="Loại phòng",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Trống"), (1, "Đang phục vụ"), (2, "Bảo trì")],
                        default=0,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "max_capacity",
                    models.IntegerField(default=1, verbose_name="Sức chứa"),
                ),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Hoạt động"),
                ),
            ],
            options={
                "verbose_name": "Phòng",
                "verbose_name_plural": "Phòng",
                "db_table": "spa_rooms",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Tên nhóm")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Hoạt động"),
                ),
            ],
            options={
                "verbose_name": "Nhóm dịch vụ",
                "verbose_name_plural": "Nhóm dịch vụ",
                "db_table": "spa_service_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Mã NV"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Họ tên")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="SĐT"
                    ),
                ),
                (
                    "position",
                    models.IntegerField(
                        choices=[(1, "Kỹ thuật viên"), (2, "Quản lý"), (3, "Lễ tân")],
                        default=1,
                        verbose_name="Chức vụ",
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="% Hoa hồng",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="staff/", verbose_name="Ảnh"
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang làm việc"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Nhân viên",
                "verbose_name_plural": "Nhân viên",
                "db_table": "spa_staff",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Mã lịch hẹn"
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Tên khách (vãng lai)",
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="SĐT khách"
                    ),
                ),
                ("booking_date", models.DateField(verbose_name="Ngày hẹn")),
                ("start_time", models.TimeField(verbose_name="Giờ bắt đầu")),
                (
                    "end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Giờ kết thúc"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Đặt trước"),
                            (1, "Đang phục vụ"),
                            (2, "Hoàn thành"),
                            (3, "Hủy"),
                        ],
                        default=0,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Tổng tiền",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Giảm giá",
                    ),
                ),
                (
                    "final_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Thành tiền",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Đã thanh toán",
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Hoa hồng KTV",
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="customers.customer",
                        verbose_name="Khách hàng",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="spa.room",
                        verbose_name="Phòng",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="spa.staff",
                        verbose_name="KTV phụ trách",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lịch hẹn",
                "verbose_name_plural": "Lịch hẹn",
                "db_table": "spa_bookings",
                "ordering": ["-booking_date", "-start_time"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Mã DV"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Tên dịch vụ")),
                (
                    "duration_minutes",
                    models.IntegerField(default=60, verbose_name="Thời lượng (phút)"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Giá dịch vụ",
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="% Hoa hồng riêng (ưu tiên)",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="services/",
                        verbose_name="Hình ảnh",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="services",
                        to="spa.servicecategory",
                        verbose_name="Nhóm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dịch vụ",
                "verbose_name_plural": "Dịch vụ",
                "db_table": "spa_services",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BookingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="Số lượng")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Đơn giá",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Thành tiền",
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Hoa hồng",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="spa.booking",
                        verbose_name="Lịch hẹn",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_items",
                        to="spa.service",
                        verbose_name="Dịch vụ",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking_items",
                        to="spa.staff",
                        verbose_name="KTV thực hiện",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chi tiết dịch vụ",
                "verbose_name_plural": "Chi tiết dịch vụ",
                "db_table": "spa_booking_items",
            },
        ),
    ]
