# Generated by Django 6.0.1 on 2026-03-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_recipients",
                    models.TextField(
                        help_text="Nhiều email phân cách bởi dấu phẩy",
                        verbose_name="Danh sách email nhận cảnh báo",
                    ),
                ),
                (
                    "alert_on_min",
                    models.BooleanField(
                        default=True, verbose_name="Cảnh báo khi dưới tồn kho tối thiểu"
                    ),
                ),
                (
                    "alert_on_max",
                    models.BooleanField(
                        default=True, verbose_name="Cảnh báo khi trên tồn kho tối đa"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                (
                    "last_sent",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Lần gửi cuối"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cấu hình cảnh báo tồn kho",
                "verbose_name_plural": "Cấu hình cảnh báo tồn kho",
                "db_table": "stock_alerts",
            },
        ),
    ]
