# Generated by Django 6.0.1 on 2026-03-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ngày xóa"),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Đã xóa"),
        ),
        migrations.AddField(
            model_name="customergroup",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ngày xóa"),
        ),
        migrations.AddField(
            model_name="customergroup",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Đã xóa"),
        ),
    ]
