# Generated by Django 6.0.1 on 2026-03-17 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_customer_deleted_at_customer_is_deleted_and_more"),
        ("system_management", "0005_userprofile_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers",
                to="system_management.store",
                verbose_name="Cửa hàng",
            ),
        ),
    ]
