# Generated by Django 6.0.1 on 2026-03-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_customer_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="company_address",
            field=models.TextField(
                blank=True, null=True, verbose_name="Địa chỉ công ty"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="customer_type",
            field=models.IntegerField(
                choices=[(1, "Cá nhân"), (2, "Công ty")],
                default=1,
                verbose_name="Loại khách hàng",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="id_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="CCCD/CMND"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="company",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Tên công ty"
            ),
        ),
    ]
