# Generated by Django 6.0.1 on 2026-03-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_customer_company_address_customer_customer_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="owner_tax_code",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="MST cá nhân chủ hộ"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="customer_type",
            field=models.IntegerField(
                choices=[(1, "Cá nhân"), (2, "Công ty"), (3, "Hộ kinh doanh")],
                default=1,
                verbose_name="Loại khách hàng",
            ),
        ),
    ]
