# Generated by Django 6.0.1 on 2026-03-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_customer_owner_tax_code_alter_customer_customer_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="customers/avatars/",
                verbose_name="Ảnh đại diện",
            ),
        ),
    ]
