# Generated by Django 6.0.1 on 2026-03-19 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0006_customer_avatar"),
        ("orders", "0011_add_approval_status_to_order"),
        ("system_management", "0010_businessconfig_mod_cafe_tables_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Ngày sinh"),
        ),
        migrations.AddField(
            model_name="customer",
            name="gender",
            field=models.IntegerField(
                choices=[(0, "Khác"), (1, "Nam"), (2, "Nữ")],
                default=0,
                verbose_name="Giới tính",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="membership_level",
            field=models.IntegerField(
                choices=[
                    (0, "Thường"),
                    (1, "Bạc"),
                    (2, "Vàng"),
                    (3, "Bạch kim"),
                    (4, "Kim cương"),
                ],
                default=0,
                verbose_name="Hạng thành viên",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="points",
            field=models.IntegerField(default=0, verbose_name="Điểm tích lũy"),
        ),
        migrations.CreateModel(
            name="PointTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.IntegerField(
                        choices=[(1, "Cộng điểm"), (2, "Đổi điểm"), (3, "Điều chỉnh")],
                        default=1,
                        verbose_name="Loại",
                    ),
                ),
                ("points", models.IntegerField(default=0, verbose_name="Số điểm")),
                (
                    "balance_after",
                    models.IntegerField(default=0, verbose_name="Điểm sau GD"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Mô tả"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="point_txns_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_transactions",
                        to="customers.customer",
                        verbose_name="Khách hàng",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="point_transactions",
                        to="orders.order",
                        verbose_name="Đơn hàng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Giao dịch điểm",
                "verbose_name_plural": "Giao dịch điểm",
                "db_table": "point_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CafeTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=20, verbose_name="Số bàn")),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Tên bàn"
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("indoor", "Trong nhà"),
                            ("outdoor", "Ngoài trời"),
                            ("vip", "Phòng VIP"),
                            ("bar", "Quầy bar"),
                        ],
                        default="indoor",
                        max_length=20,
                        verbose_name="Khu vực",
                    ),
                ),
                ("capacity", models.IntegerField(default=4, verbose_name="Số ghế")),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Trống"),
                            (1, "Đang phục vụ"),
                            (2, "Đã đặt trước"),
                            (3, "Bảo trì"),
                        ],
                        default=0,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Ghi chú"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Hoạt động"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Thứ tự")),
                (
                    "current_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tables",
                        to="orders.order",
                        verbose_name="Đơn hiện tại",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cafe_tables",
                        to="system_management.store",
                        verbose_name="Cửa hàng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bàn cafe",
                "verbose_name_plural": "Bàn cafe",
                "db_table": "cafe_tables",
                "ordering": ["sort_order", "number"],
                "unique_together": {("store", "number")},
            },
        ),
    ]
