# Generated by Django 6.0.1 on 2026-06-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0007_customer_date_of_birth_customer_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customergroup",
            name="code",
            field=models.CharField(
                blank=True, max_length=50, null=True, unique=True, verbose_name="Mã nhóm"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="amount_to_next_membership",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=18,
                verbose_name="Giá trị còn lại để lên hạng",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="contact_email",
            field=models.CharField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Email người liên hệ",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="contact_person",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Người liên hệ",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="SĐT người liên hệ",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="default_discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Chiết khấu mặc định (%)",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="default_payment_method",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Phương thức thanh toán mặc định",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="default_price_policy",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Chính sách giá mặc định",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="district",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Quận huyện"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="fax",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Fax"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="last_purchase_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Ngày mua cuối cùng"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="membership_expiry_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Ngày hết hạn thẻ"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="order_count",
            field=models.IntegerField(default=0, verbose_name="Số lượng đơn hàng"),
        ),
        migrations.AddField(
            model_name="customer",
            name="promotion_policy",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Áp dụng ưu đãi",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="province",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Tỉnh thành"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="total_product_quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="Tổng SL sản phẩm đã mua",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="total_returned_product_quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="Tổng SL sản phẩm hoàn trả",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="ward",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Phường xã"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="website",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Website"
            ),
        ),
    ]
