# Generated by Django 6.0.1 on 2026-06-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0008_customer_import_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="imported_legacy_metrics",
            field=models.BooleanField(default=False, verbose_name="Dữ liệu chỉ số lịch sử import"),
        ),
    ]
