# Generated by Django 6.0.1 on 2026-06-30 11:20

import unicodedata

from django.db import migrations, models


RETAIL = "retail"
WHOLESALE = "wholesale"
OTHER = "other"
GUEST_CUSTOMER_CODE_PREFIX = "KHLE-"
RETAIL_GROUP_KEYWORDS = ("lẻ", "le", "bán lẻ", "ban le", "retail")
WHOLESALE_GROUP_KEYWORDS = (
    "sỉ", "si", "buôn", "buon", "bán buôn", "ban buon",
    "đại lý", "dai ly", "wholesale",
)


def _normalize_text(value):
    text = str(value or "").casefold()
    text = "".join(
        char for char in unicodedata.normalize("NFKD", text)
        if not unicodedata.combining(char)
    )
    return text.replace("đ", "d")


def _infer_customer_kind(customer):
    if (customer.code or "").startswith(GUEST_CUSTOMER_CODE_PREFIX):
        return RETAIL

    group_name = ""
    if getattr(customer, "group", None):
        group_name = customer.group.name or ""

    normalized_group = _normalize_text(group_name)
    if any(keyword in normalized_group for keyword in ("si", "buon", "ban buon", "dai ly", "wholesale")):
        return WHOLESALE
    if any(keyword in normalized_group for keyword in ("le", "ban le", "retail")):
        return RETAIL
    return OTHER


def forwards(apps, schema_editor):
    Customer = apps.get_model("customers", "Customer")
    for customer in Customer.objects.select_related("group").all().iterator():
        customer.customer_kind = _infer_customer_kind(customer)
        customer.save(update_fields=["customer_kind"])


def backwards(apps, schema_editor):
    Customer = apps.get_model("customers", "Customer")
    Customer.objects.all().update(customer_kind="")


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0009_customer_imported_legacy_metrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="customer_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    (RETAIL, "Khách lẻ"),
                    (WHOLESALE, "Khách buôn / sỉ"),
                    (OTHER, "Khác / chưa phân loại"),
                ],
                default="",
                max_length=20,
                verbose_name="Khách buôn/lẻ",
            ),
        ),
        migrations.RunPython(forwards, backwards),
    ]
