from django.urls import path
from . import views

urlpatterns = [
    # Pages
    path('product_tbl/', views.product_tbl, name='product_tbl'),
    path('warehouse_tbl/', views.warehouse_tbl, name='warehouse_tbl'),
    path('purchase_order_tbl/', views.purchase_order_tbl, name='purchase_order_tbl'),
    path('goods_receipt_tbl/', views.goods_receipt_tbl, name='goods_receipt_tbl'),
    path('stock_check_tbl/', views.stock_check_tbl, name='stock_check_tbl'),
    path('stock_transfer_tbl/', views.stock_transfer_tbl, name='stock_transfer_tbl'),
    path('supplier_tbl/', views.supplier_tbl, name='supplier_tbl'),
    path('cost_adjustment_tbl/', views.cost_adjustment_tbl, name='cost_adjustment_tbl'),
    # APIs
    path('api/products/', views.api_get_products, name='api_get_products'),
    path('api/products/save/', views.api_save_product, name='api_save_product'),
    path('api/products/delete/', views.api_delete_product, name='api_delete_product'),
    path('api/warehouses/', views.api_get_warehouses, name='api_get_warehouses'),
    path('api/warehouses/save/', views.api_save_warehouse, name='api_save_warehouse'),
    path('api/warehouses/delete/', views.api_delete_warehouse, name='api_delete_warehouse'),
    path('api/suppliers/', views.api_get_suppliers, name='api_get_suppliers'),
    path('api/suppliers/save/', views.api_save_supplier, name='api_save_supplier'),
    path('api/suppliers/delete/', views.api_delete_supplier, name='api_delete_supplier'),
    path('api/categories/', views.api_get_categories, name='api_get_categories'),
    path('api/categories/save/', views.api_save_category, name='api_save_category'),
    path('api/goods_receipts/', views.api_get_goods_receipts, name='api_get_goods_receipts'),
    path('api/goods_receipts/save/', views.api_save_goods_receipt, name='api_save_goods_receipt'),
    path('api/goods_receipts/delete/', views.api_delete_goods_receipt, name='api_delete_goods_receipt'),
    path('api/stock_transfers/', views.api_get_stock_transfers, name='api_get_stock_transfers'),
    path('api/stock_transfers/save/', views.api_save_stock_transfer, name='api_save_stock_transfer'),
    path('api/stock_transfers/delete/', views.api_delete_stock_transfer, name='api_delete_stock_transfer'),
    path('api/stock_checks/', views.api_get_stock_checks, name='api_get_stock_checks'),
    path('api/stock_checks/save/', views.api_save_stock_check, name='api_save_stock_check'),
    path('api/stock_checks/delete/', views.api_delete_stock_check, name='api_delete_stock_check'),
    path('api/purchase_orders/', views.api_get_purchase_orders, name='api_get_purchase_orders'),
    path('api/purchase_orders/save/', views.api_save_purchase_order, name='api_save_purchase_order'),
    path('api/purchase_orders/delete/', views.api_delete_purchase_order, name='api_delete_purchase_order'),
    path('api/cost_adjustments/', views.api_get_cost_adjustments, name='api_get_cost_adjustments'),
    path('api/products/purchase_history/', views.api_product_purchase_history, name='api_product_purchase_history'),
]
