from django.urls import path
from . import views

urlpatterns = [
    # Pages
    path('product-tbl/', views.product_tbl, name='product_tbl'),
    path('warehouse-tbl/', views.warehouse_tbl, name='warehouse_tbl'),
    path('purchase-order-tbl/', views.purchase_order_tbl, name='purchase_order_tbl'),
    path('goods-receipt-tbl/', views.goods_receipt_tbl, name='goods_receipt_tbl'),
    path('stock-check-tbl/', views.stock_check_tbl, name='stock_check_tbl'),
    path('stock-transfer-tbl/', views.stock_transfer_tbl, name='stock_transfer_tbl'),
    path('supplier-tbl/', views.supplier_tbl, name='supplier_tbl'),
    path('cost-adjustment-tbl/', views.cost_adjustment_tbl, name='cost_adjustment_tbl'),
    # APIs
    path('api/products/', views.api_get_products, name='api_get_products'),
    path('api/products/save/', views.api_save_product, name='api_save_product'),
    path('api/products/delete/', views.api_delete_product, name='api_delete_product'),
    path('api/warehouses/', views.api_get_warehouses, name='api_get_warehouses'),
    path('api/warehouses/save/', views.api_save_warehouse, name='api_save_warehouse'),
    path('api/warehouses/delete/', views.api_delete_warehouse, name='api_delete_warehouse'),
    path('api/suppliers/', views.api_get_suppliers, name='api_get_suppliers'),
    path('api/suppliers/save/', views.api_save_supplier, name='api_save_supplier'),
    path('api/suppliers/delete/', views.api_delete_supplier, name='api_delete_supplier'),
    path('api/categories/', views.api_get_categories, name='api_get_categories'),
    path('api/categories/save/', views.api_save_category, name='api_save_category'),
    path('api/goods-receipts/', views.api_get_goods_receipts, name='api_get_goods_receipts'),
    path('api/goods-receipts/save/', views.api_save_goods_receipt, name='api_save_goods_receipt'),
    path('api/goods-receipts/delete/', views.api_delete_goods_receipt, name='api_delete_goods_receipt'),
    path('api/stock-transfers/', views.api_get_stock_transfers, name='api_get_stock_transfers'),
    path('api/stock-transfers/save/', views.api_save_stock_transfer, name='api_save_stock_transfer'),
    path('api/stock-transfers/delete/', views.api_delete_stock_transfer, name='api_delete_stock_transfer'),
    path('api/stock-checks/', views.api_get_stock_checks, name='api_get_stock_checks'),
    path('api/stock-checks/save/', views.api_save_stock_check, name='api_save_stock_check'),
    path('api/stock-checks/delete/', views.api_delete_stock_check, name='api_delete_stock_check'),
    path('api/purchase-orders/', views.api_get_purchase_orders, name='api_get_purchase_orders'),
    path('api/purchase-orders/save/', views.api_save_purchase_order, name='api_save_purchase_order'),
    path('api/purchase-orders/delete/', views.api_delete_purchase_order, name='api_delete_purchase_order'),
    path('api/cost-adjustments/', views.api_get_cost_adjustments, name='api_get_cost_adjustments'),
    path('api/products/purchase-history/', views.api_product_purchase_history, name='api_product_purchase_history'),
    path('api/products/sales-history/', views.api_product_sales_history, name='api_product_sales_history'),
    path('api/locations/', views.api_get_locations, name='api_get_locations'),
    path('api/locations/save/', views.api_save_location, name='api_save_location'),
    path('api/locations/delete/', views.api_delete_location, name='api_delete_location'),
    path('api/products/export-excel/', views.export_products_excel, name='export_products_excel'),
    path('api/goods-receipts/export-excel/', views.export_goods_receipts_excel, name='export_goods_receipts_excel'),
    path('api/stock-transfers/export-excel/', views.export_stock_transfers_excel, name='export_stock_transfers_excel'),
    path('api/stock-checks/export-excel/', views.export_stock_checks_excel, name='export_stock_checks_excel'),
    path('api/purchase-orders/export-excel/', views.export_purchase_orders_excel, name='export_purchase_orders_excel'),
    path('api/suppliers/export-excel/', views.export_suppliers_excel, name='export_suppliers_excel'),
]
