# Generated by Django 6.0.1 on 2026-03-14 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Mã đơn hàng"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Nháp"),
                            (1, "Xác nhận"),
                            (2, "Đang xử lý"),
                            (3, "Đang đóng gói"),
                            (4, "Đã giao"),
                            (5, "Hoàn thành"),
                            (6, "Hủy"),
                        ],
                        default=0,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "payment_status",
                    models.IntegerField(
                        choices=[
                            (0, "Chưa thanh toán"),
                            (1, "Thanh toán một phần"),
                            (2, "Đã thanh toán"),
                        ],
                        default=0,
                        verbose_name="Trạng thái thanh toán",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=18,
                        verbose_name="Tổng tiền hàng",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=18,
                        verbose_name="Chiết khấu",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=18, verbose_name="Thuế"
                    ),
                ),
                (
                    "final_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=18,
                        verbose_name="Tổng thanh toán",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=18,
                        verbose_name="Đã thanh toán",
                    ),
                ),
                (
                    "shipping_address",
                    models.TextField(
                        blank=True, null=True, verbose_name="Địa chỉ giao"
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
                ),
                ("order_date", models.DateField(verbose_name="Ngày đặt hàng")),
                (
                    "delivery_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày giao hàng"
                    ),
                ),
                (
                    "below_listed_price_warning",
                    models.BooleanField(
                        default=False, verbose_name="Cảnh báo dưới giá niêm yết"
                    ),
                ),
                (
                    "warning_email_sent",
                    models.BooleanField(
                        default=False, verbose_name="Đã gửi mail cảnh báo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="customers.customer",
                        verbose_name="Khách hàng",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="products.warehouse",
                        verbose_name="Kho xuất",
                    ),
                ),
            ],
            options={
                "verbose_name": "Đơn hàng",
                "verbose_name_plural": "Đơn hàng",
                "db_table": "orders",
                "ordering": ["-order_date"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="Số lượng")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Đơn giá",
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Giá vốn",
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Chiết khấu (%)",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Thành tiền",
                    ),
                ),
                (
                    "is_below_listed",
                    models.BooleanField(
                        default=False, verbose_name="Dưới giá niêm yết"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="Đơn hàng",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="products.product",
                        verbose_name="Sản phẩm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chi tiết đơn hàng",
                "verbose_name_plural": "Chi tiết đơn hàng",
                "db_table": "order_items",
            },
        ),
        migrations.CreateModel(
            name="OrderReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Mã phiếu trả"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Nháp"),
                            (1, "Xác nhận"),
                            (2, "Hoàn thành"),
                            (3, "Hủy"),
                        ],
                        default=0,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "total_refund",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=18,
                        verbose_name="Tổng hoàn trả",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Lý do trả hàng"
                    ),
                ),
                ("return_date", models.DateField(verbose_name="Ngày trả hàng")),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="returns_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="returns",
                        to="customers.customer",
                        verbose_name="Khách hàng",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="returns",
                        to="orders.order",
                        verbose_name="Đơn hàng gốc",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="returns",
                        to="products.warehouse",
                        verbose_name="Kho nhận",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phiếu trả hàng",
                "verbose_name_plural": "Phiếu trả hàng",
                "db_table": "order_returns",
                "ordering": ["-return_date"],
            },
        ),
        migrations.CreateModel(
            name="OrderReturnItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(default=0, verbose_name="Số lượng trả"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Đơn giá",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Thành tiền",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, null=True, verbose_name="Lý do"),
                ),
                (
                    "order_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.orderreturn",
                        verbose_name="Phiếu trả",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_items",
                        to="products.product",
                        verbose_name="Sản phẩm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chi tiết trả hàng",
                "verbose_name_plural": "Chi tiết trả hàng",
                "db_table": "order_return_items",
            },
        ),
        migrations.CreateModel(
            name="Packaging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Mã đóng gói"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Chờ đóng gói"),
                            (1, "Đang đóng gói"),
                            (2, "Hoàn thành"),
                            (3, "Hủy"),
                        ],
                        default=0,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Trọng lượng (kg)",
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
                ),
                (
                    "packed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Thời gian đóng gói"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packagings",
                        to="orders.order",
                        verbose_name="Đơn hàng",
                    ),
                ),
                (
                    "packed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="packagings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người đóng gói",
                    ),
                ),
            ],
            options={
                "verbose_name": "Đóng gói",
                "verbose_name_plural": "Đóng gói",
                "db_table": "packagings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Mã báo giá"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Nháp"),
                            (1, "Đã gửi"),
                            (2, "Đã duyệt"),
                            (3, "Đã tạo đơn hàng"),
                            (4, "Hủy"),
                        ],
                        default=0,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=18,
                        verbose_name="Tổng tiền",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=18,
                        verbose_name="Chiết khấu",
                    ),
                ),
                (
                    "final_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=18,
                        verbose_name="Thành tiền",
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True, null=True, verbose_name="Hiệu lực đến"
                    ),
                ),
                ("quotation_date", models.DateField(verbose_name="Ngày báo giá")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotations",
                        to="customers.customer",
                        verbose_name="Khách hàng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Báo giá",
                "verbose_name_plural": "Báo giá",
                "db_table": "quotations",
                "ordering": ["-quotation_date"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="quotation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="orders.quotation",
                verbose_name="Báo giá",
            ),
        ),
        migrations.CreateModel(
            name="QuotationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="Số lượng")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Đơn giá",
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Chiết khấu (%)",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Thành tiền",
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotation_items",
                        to="products.product",
                        verbose_name="Sản phẩm",
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.quotation",
                        verbose_name="Báo giá",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chi tiết báo giá",
                "verbose_name_plural": "Chi tiết báo giá",
                "db_table": "quotation_items",
            },
        ),
    ]
