# Generated by Django 6.0.1 on 2026-03-17 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_deleted_at_order_is_deleted_and_more"),
        ("products", "0003_productvariant"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="products.productvariant",
                verbose_name="Biến thể",
            ),
        ),
    ]
