# Generated by Django 6.0.1 on 2026-03-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_quotationitem_variant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=15, verbose_name="Số lượng"
            ),
        ),
        migrations.AlterField(
            model_name="quotationitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=15, verbose_name="Số lượng"
            ),
        ),
    ]
