# Generated by Django 6.0.1 on 2026-03-17 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_orderitem_quantity_and_more"),
        ("system_management", "0005_userprofile_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="system_management.store",
                verbose_name="Cửa hàng",
            ),
        ),
    ]
