# Generated by Django 6.0.1 on 2026-03-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="salesperson",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Người báo giá"
            ),
        ),
    ]
