# Generated by Django 6.0.1 on 2026-03-17 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_quotation_salesperson"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders_approved",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người duyệt",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="bonus_amount",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=18, verbose_name="Tiền bonus"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="creator_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Người tạo hóa đơn"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="salesperson",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nhân viên bán hàng"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="server_staff",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nhân viên phục vụ"
            ),
        ),
    ]
