# Generated by Django 6.0.1 on 2026-03-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0008_order_approver_order_bonus_amount_order_creator_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="server_staff",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Nhân viên phục vụ"
            ),
        ),
    ]
