# Generated by Django 6.0.1 on 2026-03-18 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_alter_order_server_staff"),
        ("system_management", "0009_businessconfig_opt_order_approver"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotations",
                to="system_management.store",
                verbose_name="Cửa hàng",
            ),
        ),
    ]
