# Generated by Django 6.0.1 on 2026-03-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_add_store_to_quotation"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="approval_status",
            field=models.IntegerField(
                choices=[
                    (0, "Không cần duyệt"),
                    (1, "Chờ duyệt"),
                    (2, "Đã duyệt"),
                    (3, "Từ chối"),
                ],
                default=0,
                verbose_name="Trạng thái duyệt",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Thời gian duyệt"
            ),
        ),
    ]
