# Generated by Django 4.2.28 on 2026-04-13 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0011_add_approval_status_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Phí vận chuyển'),
        ),
        migrations.AddField(
            model_name='order',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Phí vận chuyển'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='OrderEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Tạo đơn'), ('update', 'Cập nhật đơn'), ('note', 'Sửa ghi chú'), ('cancel', 'Hủy đơn'), ('approve', 'Duyệt đơn'), ('reject', 'Từ chối duyệt'), ('bulk_collect', 'Thanh toán nhanh'), ('bulk_cancel', 'Hủy nhanh')], max_length=30, verbose_name='Hành động')),
                ('status_before', models.IntegerField(blank=True, null=True, verbose_name='Trạng thái trước')),
                ('status_after', models.IntegerField(blank=True, null=True, verbose_name='Trạng thái sau')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Diễn giải')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_edit_histories', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='orders.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Lịch sử đơn hàng',
                'verbose_name_plural': 'Lịch sử đơn hàng',
                'db_table': 'order_edit_histories',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
