# Generated by Django 6.0.1 on 2026-05-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_service_line_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Báo giá"),
                    (1, "Đơn hàng"),
                    (2, "Đang xử lý"),
                    (3, "Đang đóng gói"),
                    (4, "Đã xuất kho"),
                    (5, "Hoàn thành"),
                    (6, "Hủy"),
                ],
                default=0,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.AlterField(
            model_name="orderedithistory",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Tạo đơn"),
                    ("update", "Cập nhật đơn"),
                    ("note", "Sửa ghi chú"),
                    ("cancel", "Hủy đơn"),
                    ("approve", "Duyệt đơn"),
                    ("reject", "Từ chối duyệt"),
                    ("status", "Đổi trạng thái"),
                    ("bulk_collect", "Thanh toán nhanh"),
                    ("bulk_cancel", "Hủy nhanh"),
                ],
                max_length=30,
                verbose_name="Hành động",
            ),
        ),
    ]
