# Generated by Django 6.0.1 on 2026-05-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0015_demote_unpaid_completed_orders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderedithistory",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Tạo đơn"),
                    ("update", "Cập nhật đơn"),
                    ("note", "Sửa ghi chú"),
                    ("cancel", "Hủy đơn"),
                    ("approve", "Duyệt đơn"),
                    ("reject", "Từ chối duyệt"),
                    ("status", "Đổi trạng thái"),
                    ("payment", "Thu tiền"),
                    ("stock_export", "Xuất kho"),
                    ("return", "Hoàn hàng"),
                    ("bulk_collect", "Thanh toán nhanh"),
                    ("bulk_cancel", "Hủy nhanh"),
                ],
                max_length=30,
                verbose_name="Hành động",
            ),
        ),
    ]
