# Generated by Codex on 2026-05-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_orderedithistory_action'),
        ('products', '0014_productlocation_and_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreturn',
            name='amount_due',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Còn phải thu'),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='compensation_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Hoàn tiền/đền bù riêng'),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='exchange_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Tổng hàng đổi'),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='exchange_note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú đổi hàng'),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='return_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Tổng hàng trả'),
        ),
        migrations.CreateModel(
            name='OrderReturnExchangeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=15, verbose_name='Số lượng đổi')),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Đơn giá')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Chiết khấu (%)')),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Thành tiền')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('order_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_items', to='orders.orderreturn', verbose_name='Phiếu trả')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_exchange_items', to='products.product', verbose_name='Sản phẩm đổi')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_exchange_items', to='products.productvariant', verbose_name='Biến thể')),
            ],
            options={
                'verbose_name': 'Chi tiết đổi hàng',
                'verbose_name_plural': 'Chi tiết đổi hàng',
                'db_table': 'order_return_exchange_items',
            },
        ),
    ]
