# Generated by Django 6.0.1 on 2026-07-03 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0018_orderreturn_exchange_order"),
        ("system_management", "0019_printersetting_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="issuing_brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders_issued",
                to="system_management.brand",
                verbose_name="Nhãn hiệu in",
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="issuing_brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotations_issued",
                to="system_management.brand",
                verbose_name="Nhãn hiệu in",
            ),
        ),
    ]
