# Generated by Django 6.0.1 on 2026-03-14 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoodsReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Mã phiếu nhập"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Nháp"), (1, "Hoàn thành"), (2, "Hủy")],
                        default=0,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Tổng tiền",
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
                ),
                ("receipt_date", models.DateField(verbose_name="Ngày nhập")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goods_receipts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Phiếu nhập kho",
                "verbose_name_plural": "Phiếu nhập kho",
                "db_table": "goods_receipts",
                "ordering": ["-receipt_date"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Mã sản phẩm"
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Barcode"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Tên sản phẩm")),
                (
                    "unit",
                    models.CharField(
                        default="Cái", max_length=50, verbose_name="Đơn vị tính"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/",
                        verbose_name="Hình ảnh",
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Giá vốn",
                    ),
                ),
                (
                    "listed_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Giá niêm yết",
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Giá bán",
                    ),
                ),
                (
                    "min_stock",
                    models.IntegerField(default=0, verbose_name="Tồn kho tối thiểu"),
                ),
                (
                    "max_stock",
                    models.IntegerField(default=0, verbose_name="Tồn kho tối đa"),
                ),
                (
                    "sapo_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Mã SAPO"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sản phẩm",
                "verbose_name_plural": "Sản phẩm",
                "db_table": "products",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GoodsReceiptItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(default=0, verbose_name="Số lượng nhập"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Đơn giá",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Thành tiền",
                    ),
                ),
                (
                    "goods_receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="products.goodsreceipt",
                        verbose_name="Phiếu nhập",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt_items",
                        to="products.product",
                        verbose_name="Sản phẩm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chi tiết phiếu nhập",
                "verbose_name_plural": "Chi tiết phiếu nhập",
                "db_table": "goods_receipt_items",
            },
        ),
        migrations.CreateModel(
            name="CostAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_cost",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Giá vốn cũ",
                    ),
                ),
                (
                    "new_cost",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Giá vốn mới",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, null=True, verbose_name="Lý do"),
                ),
                (
                    "adjusted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ngày điều chỉnh"
                    ),
                ),
                (
                    "adjusted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cost_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_adjustments",
                        to="products.product",
                        verbose_name="Sản phẩm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Điều chỉnh giá vốn",
                "verbose_name_plural": "Điều chỉnh giá vốn",
                "db_table": "cost_adjustments",
                "ordering": ["-adjusted_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Tên danh mục")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="products.productcategory",
                        verbose_name="Danh mục cha",
                    ),
                ),
            ],
            options={
                "verbose_name": "Danh mục sản phẩm",
                "verbose_name_plural": "Danh mục sản phẩm",
                "db_table": "product_categories",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.productcategory",
                verbose_name="Danh mục",
            ),
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Mã đơn đặt hàng"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Nháp"),
                            (1, "Đã gửi"),
                            (2, "Đã nhận hàng"),
                            (3, "Hoàn thành"),
                            (4, "Hủy"),
                        ],
                        default=0,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Tổng tiền",
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
                ),
                ("order_date", models.DateField(verbose_name="Ngày đặt hàng")),
                (
                    "expected_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày dự kiến nhận"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_orders_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Đơn đặt hàng nhập",
                "verbose_name_plural": "Đơn đặt hàng nhập",
                "db_table": "purchase_orders",
                "ordering": ["-order_date"],
            },
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="goods_receipts",
                to="products.purchaseorder",
                verbose_name="Đơn đặt hàng",
            ),
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(default=0, verbose_name="Số lượng đặt"),
                ),
                (
                    "received_quantity",
                    models.IntegerField(default=0, verbose_name="Số lượng nhận"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Đơn giá",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Thành tiền",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_items",
                        to="products.product",
                        verbose_name="Sản phẩm",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="products.purchaseorder",
                        verbose_name="Đơn đặt hàng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chi tiết đơn đặt hàng",
                "verbose_name_plural": "Chi tiết đơn đặt hàng",
                "db_table": "purchase_order_items",
            },
        ),
        migrations.CreateModel(
            name="StockCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Mã phiếu kiểm"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Đang kiểm"), (1, "Hoàn thành"), (2, "Hủy")],
                        default=0,
                        verbose_name="Trạng thái",
                    ),
                ),
                ("check_date", models.DateField(verbose_name="Ngày kiểm")),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_checks_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Phiếu kiểm kê",
                "verbose_name_plural": "Phiếu kiểm kê",
                "db_table": "stock_checks",
                "ordering": ["-check_date"],
            },
        ),
        migrations.CreateModel(
            name="StockCheckItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system_quantity",
                    models.IntegerField(default=0, verbose_name="Tồn hệ thống"),
                ),
                (
                    "actual_quantity",
                    models.IntegerField(default=0, verbose_name="Tồn thực tế"),
                ),
                (
                    "difference",
                    models.IntegerField(default=0, verbose_name="Chênh lệch"),
                ),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_items",
                        to="products.product",
                        verbose_name="Sản phẩm",
                    ),
                ),
                (
                    "stock_check",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="products.stockcheck",
                        verbose_name="Phiếu kiểm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chi tiết kiểm kê",
                "verbose_name_plural": "Chi tiết kiểm kê",
                "db_table": "stock_check_items",
            },
        ),
        migrations.CreateModel(
            name="StockTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Mã phiếu chuyển"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Nháp"),
                            (1, "Đang chuyển"),
                            (2, "Hoàn thành"),
                            (3, "Hủy"),
                        ],
                        default=0,
                        verbose_name="Trạng thái",
                    ),
                ),
                ("transfer_date", models.DateField(verbose_name="Ngày chuyển")),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Phiếu chuyển kho",
                "verbose_name_plural": "Phiếu chuyển kho",
                "db_table": "stock_transfers",
                "ordering": ["-transfer_date"],
            },
        ),
        migrations.CreateModel(
            name="StockTransferItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0, verbose_name="Số lượng")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_items",
                        to="products.product",
                        verbose_name="Sản phẩm",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="products.stocktransfer",
                        verbose_name="Phiếu chuyển",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chi tiết chuyển kho",
                "verbose_name_plural": "Chi tiết chuyển kho",
                "db_table": "stock_transfer_items",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Mã NCC"),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Tên nhà cung cấp"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Số điện thoại",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Địa chỉ"),
                ),
                (
                    "tax_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Mã số thuế"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Người liên hệ",
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suppliers_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Nhà cung cấp",
                "verbose_name_plural": "Nhà cung cấp",
                "db_table": "suppliers",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_orders",
                to="products.supplier",
                verbose_name="Nhà cung cấp",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.supplier",
                verbose_name="Nhà cung cấp",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="goods_receipts",
                to="products.supplier",
                verbose_name="Nhà cung cấp",
            ),
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Mã kho"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Tên kho")),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Địa chỉ"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_warehouses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Quản lý kho",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kho",
                "verbose_name_plural": "Kho",
                "db_table": "warehouses",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="from_warehouse",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfers_out",
                to="products.warehouse",
                verbose_name="Kho xuất",
            ),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="to_warehouse",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfers_in",
                to="products.warehouse",
                verbose_name="Kho nhập",
            ),
        ),
        migrations.AddField(
            model_name="stockcheck",
            name="warehouse",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_checks",
                to="products.warehouse",
                verbose_name="Kho",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="warehouse",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_orders",
                to="products.warehouse",
                verbose_name="Kho nhập",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="warehouse",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="goods_receipts",
                to="products.warehouse",
                verbose_name="Kho nhập",
            ),
        ),
        migrations.CreateModel(
            name="ProductStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(default=0, verbose_name="Số lượng tồn"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="products.product",
                        verbose_name="Sản phẩm",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="products.warehouse",
                        verbose_name="Kho",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tồn kho",
                "verbose_name_plural": "Tồn kho",
                "db_table": "product_stocks",
                "unique_together": {("product", "warehouse")},
            },
        ),
    ]
