# Generated by Django 6.0.1 on 2026-03-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceipt",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ngày xóa"),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Đã xóa"),
        ),
        migrations.AddField(
            model_name="product",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ngày xóa"),
        ),
        migrations.AddField(
            model_name="product",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Đã xóa"),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ngày xóa"),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Đã xóa"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ngày xóa"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Đã xóa"),
        ),
        migrations.AddField(
            model_name="stockcheck",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ngày xóa"),
        ),
        migrations.AddField(
            model_name="stockcheck",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Đã xóa"),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ngày xóa"),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Đã xóa"),
        ),
        migrations.AddField(
            model_name="supplier",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ngày xóa"),
        ),
        migrations.AddField(
            model_name="supplier",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Đã xóa"),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ngày xóa"),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Đã xóa"),
        ),
    ]
