# Generated by Django 6.0.1 on 2026-03-15 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_goodsreceipt_deleted_at_goodsreceipt_is_deleted_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size_name",
                    models.CharField(max_length=50, verbose_name="Kích thước"),
                ),
                (
                    "sku",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Mã SKU"
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Barcode"
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Giá vốn",
                    ),
                ),
                (
                    "listed_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Giá niêm yết",
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Giá bán",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="products.product",
                        verbose_name="Sản phẩm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Biến thể sản phẩm",
                "verbose_name_plural": "Biến thể sản phẩm",
                "db_table": "product_variants",
                "ordering": ["product", "size_name"],
            },
        ),
    ]
