# Generated by Django 6.0.1 on 2026-03-17 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_productvariant"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_items",
                to="products.productvariant",
                verbose_name="Biến thể",
            ),
        ),
    ]
