# Generated by Django 6.0.1 on 2026-03-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_stockcheckitem_variant_stocktransferitem_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_weight_based",
            field=models.BooleanField(
                default=False, verbose_name="Bán theo khối lượng"
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceiptitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="Số lượng nhập"
            ),
        ),
        migrations.AlterField(
            model_name="productstock",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="Số lượng tồn"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="Số lượng đặt"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="received_quantity",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="Số lượng nhận"
            ),
        ),
        migrations.AlterField(
            model_name="stockcheckitem",
            name="actual_quantity",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="Tồn thực tế"
            ),
        ),
        migrations.AlterField(
            model_name="stockcheckitem",
            name="difference",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="Chênh lệch"
            ),
        ),
        migrations.AlterField(
            model_name="stockcheckitem",
            name="system_quantity",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="Tồn hệ thống"
            ),
        ),
        migrations.AlterField(
            model_name="stocktransferitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="Số lượng"
            ),
        ),
    ]
