# Generated by Django 6.0.1 on 2026-03-17 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_product_store"),
        ("system_management", "0006_brand_business_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="warehouses",
                to="system_management.store",
                verbose_name="Cửa hàng",
            ),
        ),
    ]
