# Generated by Django 6.0.1 on 2026-03-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_warehouse_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_service",
            field=models.BooleanField(default=False, verbose_name="Sản phẩm dịch vụ"),
        ),
    ]
