# Generated by Django 6.0.1 on 2026-03-19 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_add_is_service_to_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_combo",
            field=models.BooleanField(default=False, verbose_name="Sản phẩm combo"),
        ),
        migrations.CreateModel(
            name="ComboItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=15,
                        verbose_name="Số lượng",
                    ),
                ),
                (
                    "combo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combo_items",
                        to="products.product",
                        verbose_name="Combo",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_combos",
                        to="products.product",
                        verbose_name="Sản phẩm thành phần",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thành phần combo",
                "verbose_name_plural": "Thành phần combo",
                "db_table": "combo_items",
                "unique_together": {("combo", "product")},
            },
        ),
    ]
