# Generated by Django 6.0.1 on 2026-04-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_add_combo_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="location",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Vị trí sản phẩm"
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="size_name",
            field=models.CharField(max_length=50, verbose_name="Quy cách"),
        ),
    ]
